### PR TITLE
Adding some rudimentary stacking

### PR DESCRIPTION
**Pull request by davidcoleman007**
Hi guys, I've made this PR with my stacking mods as promised.

### CODE REVIEW

**Comment by bayleedev** [comment]
This is awesome! I'll try and look at this soon. :D

**Comment by bayleedev** [comment]
What's the behavior when it gets to the bottom of the screen? It seems those stack:

screenshot_12_9_16__3_24_pm

I set the timeout to 10 seconds, I opened 4 with a few seconds delay between each of them. When two closed, I click the button to open another and it opens in the wrong spot. You can see the first one here is overlapping:

screen shot 2016-12-09 at 3 26 09 pm

After all 4 close, I click the button again, and it appears in the second position.

**Comment by davidcoleman007** [comment]
Yeah, that’s something that I mentioned in a TODO… I don’t have any collapsing when a middle one is removed yet.  It’s a work in progress, which I’ll be working on for my personal project and then contribute here.  Will probably use jquery for a nice slide up/down effect and also utilize the maxStack property that I just have hanging in the constructor, then collapse things and pop off the stack of pending stuff which I didn’t build yet.

 

Also want to allow it to be from top or bottom depending on OS, so that it looks native to windows and mac peeps alike. :)

 

As I said, this is “rudimentary” stacking. :)

 

I intend to build this out much more over the next week or so as our project progresses.

**Comment by davidcoleman007** [comment]
Hi @blainesch I've updated this with the following changes:

* stacking now respects `maxStack`
* when a notification closes, we now will re-position all active notifications to properly fill in the gap
* fixed all the bugs you mentioned with positioning, stack management is nice now
* detect windows/!windows
  * windows shows stacks from the bottom - I've estimated start bar size as 75px as electron doesn't seem to support detecting this data
  * !windows shows from the top as you already had implemented
  * TODO: detect KDE (if we can)? KDE should show stacks from bottom to be visually consistent vs Gnome
* updated playbook with a "stacking" option and logic to execute it properly

I wanted to do some jQuery to make them fancy and collapse with everything all slick... that was a lot of work that seemed be out of place as an initial implementation.  I focused on making the stack WORK.

**Comment by davidcoleman007** [comment]
I should mention that I recently noticed that on windows the notifications are MOVABLE if I click and drag on the body of the note... maybe this shouldn't be possible?

**Comment by davidcoleman007** [comment]
New stacking playbook entry:
image

**Comment by davidcoleman007** [comment]
This is what a `maxStack == 7` looks like:
ignore the start bar overlap, b/c I have a 3 row start bar since I run on 3x QHD monitors and have a tall start bar on the middle screen.  75 px should be just fine on any std windows system.  when we have a more elegant way to detect the size of the start bar, we can use it.

image

**Comment by davidcoleman007** [comment]
also I didn't dig down into the css yet, but I feel like the gap should be configurable.  Just a thought.

maybe
```javascript
notifier.configure({
    maxStack : 7,
    stackGap: 10
});
```

**Comment by bayleedev** [comment]
The max stack should default based on the screen size.

**Comment by davidcoleman007** [comment]
I like that, and agree 100%.  yes I'll do it in the next few days!

**Comment by davidcoleman007** [comment]
ok, new plan.  I'll do it tonight!  :)

**Comment by davidcoleman007** [comment]
@blainesch is there some reason you have held off on this PR?  Is there some additional issue which you feel to be required?

**Comment by bayleedev** [comment]
Oh sorry. I saw your comment, but didn't see the commit. I'll take a look. Thank you for reminding me [:

**Comment by bayleedev** [comment]
This is great, good job! [:

**Comment by bayleedev** [comment]
Published as v0.1.5

**Pull request merged**
