### PR TITLE
Update style of notifications.

### LINKED ISSUE #15: Shows blank popup on Windows 7
Hi,

I ran the Playbook, the outline of the pop up shows us, but no content.  Could you please advise.

image

### LINKED ISSUE #18: Shows blank pop uop on Ubuntu 16.04
image

Shows up blank on Ubuntu.

[Tried setting `windowOptions.transperancy` to false](https://github.com/blainesch/electron-notifications/blob/e1fecff3129a9eb49640849a630b19b36b3b2255/lib/notifier.js#L41) . No Success

### PR DESCRIPTION
**Pull request by bayleedev**
Fixes #17
Fixes #15
Fixes #18

This gives a dark theme instead of the mac-like theme. This allows us to remove transparency and be more cross platform.

### CODE REVIEW

**Comment by afriedma** [comment]
91592f18-fe5f-11e6-9601-9e6ff58990d7

White border is visible on windows 7

**Comment by bayleedev** [comment]
@afriedma how's this? :D

**Comment by afriedma** [comment]
That's sweet, ship it..... And thanks again for a quick turnaround.

**Comment by bayleedev** [comment]
@afriedma shipped as v1.0.0

**Pull request merged**
