### PR TITLE
better macOS behaviour

### PR DESCRIPTION
**Pull request by tzapu**
unfortunately on macOS notifications steal focus, not a very good experience

### CODE REVIEW

**Comment by bayleedev** [comment]
Thanks for finding this! I'll check it out now.

**Comment by bayleedev** [comment]
Looks good to me!

**Comment by tzapu** [comment]
thank you for including this. is there any timeline for releasing on npm as well?

thanks

**Comment by bayleedev** [comment]
I published as `v0.1.3`, thanks!

**Pull request merged**
